### ISSUE TITLE
suggestion: delayed responses?

### ISSUE THREAD

**Issue by xycodex** [postmanlabs/httpbin#26]
suggestion: add the ability to delayed responses - this would be useful for testing timeouts on clients.

**Comment by lcrespom** [comment]
Hi! I know this issue is closed, but I notice that the http://httpbin.org/ website does not mention the /delay endpoint. I found about it by looking at the source code.

I don't know if this is intentional, e.g. to reduce risk of overloading the site, or an oversight.
