### ISSUE TITLE
Dedicated httpbin under basic auth

### ISSUE THREAD

**Issue by aohorodnyk** [postmanlabs/httpbin#474]
Hi,

I want to have my own HttpBin instance (because don't want to DDOS public version) for many requests. But I want to close access to my instance over basic auth, but new Swagger UI doesn't work.

Steps to reproduce:
* Make basic auth on your nginx
* Go to httpbin site
* Look at the infinity loading
* Go to Developer Tools -> Network
* Look at `Status Code: 401` on the `/spec.json` request

I can't  find `authorization: Basic ***` in the request headers

*Expected Result*:
HttpBin works, or can I protect instance in the httpbin from Docker?

**Comment by aohorodnyk** [comment]
I'm sorry, but could someone help me, please?

**Comment by javabrett** [comment]
Maybe incorporating aspects of https://github.com/rochacbruno/flasgger/blob/master/examples/basic_auth.py will help.

**Comment by aohorodnyk** [comment]
@javabrett, thanks a lot, but I’ve used the version 0.7.0 with previous design. I’ll try to do it later
