### ISSUE TITLE
Subdomain or endpoint for intentional SSL verification errors

### ISSUE THREAD

**Issue by spyoungtech** [postmanlabs/httpbin#528]
I had a thought that, as a user, it would be nice to be able to test how my client will behave when encountering SSL verification issues.

```
requests.get('https://insecure.httpbin.org/status/200')  #  expected to fail
requests.get('https://insecure.httpbin.org/status/200', verify=False)  #  g2g
```

Alternatively, you could purposely give Flask an outdated cert and allow Flask to handle SSL for just a specific endpoint or url pattern like `httpbin.org/insecure/status/200`.

Thoughts?

**Comment by sigmavirus24** [comment]
https://badssl.com/ already does this a lot better than we could
