### ISSUE TITLE
httpbin redirects to HTTPS

### ISSUE THREAD

**Issue by untitaker** [postmanlabs/httpbin#533]
HTTP used to work, now it redirects. This breaks testsuites.

Previous issue: #489

**Comment by kunagpal** [comment]
@untitaker Thanks for pointing this out, the issue has been fixed 😄

**Comment by untitaker** [comment]
Awesome, thanks for the fast response!

**Comment by cup** [comment]
https://github.com/postmanlabs/httpbin/issues/440
https://github.com/postmanlabs/httpbin/issues/489

https://github.com/postmanlabs/httpbin/issues/533
https://github.com/postmanlabs/httpbin/issues/536
https://github.com/postmanlabs/httpbin/issues/545
