### ISSUE TITLE
Hostname www.httpbin.org is dead

### ISSUE THREAD

**Issue by jeroen** [postmanlabs/httpbin#534]
As of yesterday the hostname `www.httpbin.org` is no longer reachable. Before this would point to the same host as `httpbin.org` (and unfortunately I have assumed this in some unit tests) :)

Thanks!

**Comment by bennneuh** [comment]
eu.httpbin.org is not resolvable also.

++

**Comment by kunagpal** [comment]
@jeroen @bennneuh Thanks for pointing this out, both: `www` and `eu` should be working fine now.

**Comment by jeroen** [comment]
Thanks!
