### ISSUE TITLE
Is it possible to set a response header to httpbin by passing a parameter?

### ISSUE THREAD

**Issue by JimmyCYJ** [postmanlabs/httpbin#558]
I deploys multiple httpbin instances in my GKE cluster, and each httpbin is running in a pod.
A client is sending requests that could reach any of the httpbin pods. By checking the response, I need to know that response is sent by which httpbin, and it would be helpful if I can set a unique response header to differentiate each httpbin.

**Comment by mmamaenko** [comment]
you may just add something like this
`import socket`
`hostname = socket.gethostname()`
`response.headers["Server-Name"] = hostname`
`response.headers["Server-IP"] = socket.gethostbyname(hostname)`
in set_cors_headers(response)  function in httpbin/core.py and response header will have pod name and ip
