### ISSUE TITLE
Regression: server sending invalid Content-Length for gzipped responses

### ISSUE THREAD

**Issue by jeroen** [postmanlabs/httpbin#561]
A recent change has caused my unit tests to fail, because the `Content-Length` response header does not match the length of the body.

To reproduce try for example:

```
curl --compressed -v https://eu.httpbin.org/get > out.txt
```

And then for example I see this:

```
< Content-Encoding: gzip
< Content-Type: application/json
< Date: Fri, 28 Jun 2019 23:12:32 GMT
< Referrer-Policy: no-referrer-when-downgrade
< Server: nginx
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< Content-Length: 179
```

However if we look at the file the size is actually 249 bytes instead of 179. I think the server is sending the gzipped size instead of the actual size.

**Comment by simonkowallik** [comment]
Hi, the `Content-Length: 179` describes the length transferred on "the wire".

`curl --compressed` does request compressed content and decompresses the response for you, hence the actual file size differs. See [https://curl.haxx.se/docs/manpage.html#--compressed](https://curl.haxx.se/docs/manpage.html#--compressed)

If you send the `Accept-Encoding` header with `gzip` manually and invoke `| wc -c`, you'll have confirmation for the behaviour. In this case the response does not get uncompressed for you.

```sh
curl -v https://eu.httpbin.org/get -H 'Accept-Encoding: gzip' | wc -c
...

< Content-Length: 173
< Connection: keep-alive
<
{ [173 bytes data]
100   173  100   173    0     0    434      0 --:--:-- --:--:-- --:--:--   433
* Connection #0 to host eu.httpbin.org left intact
173
```
173 bytes of content was transferred in the above request.

If you pipe the response to `gzip -d | wc -c` you'll get the uncompressed content length.
```sh
curl -v https://eu.httpbin.org/get -H 'Accept-Encoding: gzip' | gzip -d | wc -c
...

< Content-Length: 173
< Connection: keep-alive
<
{ [173 bytes data]
100   173  100   173    0     0    399      0 --:--:-- --:--:-- --:--:--   400
* Connection #0 to host eu.httpbin.org left intact
242
```

**Comment by jeroen** [comment]
Hmm maybe you are right. Older versions of httpbin used to give the uncompressed file size in the content-length: 

```
curl --compressed -v http://hb.opencpu.org/get > out.txt
```

It's quite recent that the  `Content-Length` now tells you the wire size instead of the body size.

**Comment by simonkowallik** [comment]
The `Content-Length` header provides the anticipated message body/payload size of the HTTP message. It seems like the httpbin instance on `http://hb.opencpu.org` doesn't provide compression, hence the `Content-Length` will always be the one of the uncompressed message body. While `curl --compressed` asks for compression of the response, it can't force the server to compress responses though.

Also compression is part of the configuration of the webserver serving httpbin. `eu.httpbin.org` seems to have a configuration supporting compression of responses (if the user-agent asks for it).

If the unit tests compare the `Content-Length` value and additionally calculate the message body/payload length (similar to `wc -c` above), the user-agent used in the unit tests needs to follow standards and either check the length before decompression or do not ask for compression (by not sending `Accept-Encoding`).

```sh
curl --compressed -v http://eu.httpbin.org/get
> GET /get HTTP/1.1
> Host: eu.httpbin.org
> User-Agent: curl/7.54.0
> Accept: */*
> Accept-Encoding: deflate, gzip   <--- encoding/compression algorithms accepted by user-agent
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Content-Encoding: gzip     <--- content compressed with gzip
< Content-Type: application/json
< Date: Tue, 02 Jul 2019 22:21:20 GMT
< Referrer-Policy: no-referrer-when-downgrade
< Server: nginx
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< Content-Length: 180     <--- length of compressed content (HTTP message payload)
< Connection: keep-alive
<
```
vs.

```sh
curl --compressed -v http://hb.opencpu.org/get
> GET /get HTTP/1.1
> Host: hb.opencpu.org
> User-Agent: curl/7.54.0
> Accept: */*
> Accept-Encoding: deflate, gzip   <--- encoding/compression algorithms accepted by user-agent
>
< HTTP/1.1 200 OK     <--- Content-Encoding header missing in HTTP response
< Server: nginx/1.12.0
< Date: Tue, 02 Jul 2019 22:16:56 GMT
< Content-Type: application/json
< Content-Length: 258
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< X-Powered-By: Flask
< X-Processed-Time: 0
<
```

**Comment by jeroen** [comment]
OK you are right, the `Content-Length` indeed is the wire size, not the file size.

I'm not sure how this test passed for the past years, it basically checks if the response size matches `Content-Length`. I am certain older versions of `httpbin.org` must have given the uncompressed size in `Content-Length`, even if the response was gzipped.
