### ISSUE TITLE
/delay not documented?

### ISSUE THREAD

**Issue by mlissner** [postmanlabs/httpbin#583]
I'm really sorry if I'm blind, but looking at the source doesn't have the word `delay` in it at all. Yet `/delay/2/` works. 

Should it be documented? I only found it because I had this tickling feeling in my brain that it used to exist, and then I found it mentioned here in the bug tracker.

**Comment by sgaynetdinov** [comment]
https://github.com/postmanlabs/httpbin/blob/master/httpbin/core.py#L1195

**Comment by mlissner** [comment]
Hm, perhaps github search failed me, but does it appear in the documentation?

**Comment by sgaynetdinov** [comment]
> Hm, perhaps github search failed me, but does it appear in the documentation?

https://httpbin.org/#/Dynamic_data/get_delay__delay_

Category "Dynamic data -> delay"

**Comment by sgaynetdinov** [comment]
@mlissner close?

**Comment by mlissner** [comment]
My apologies, I'm an idiot. Sorry for wasting time here. Yes, closing!

**Comment by sgaynetdinov** [comment]
> My apologies, I'm an idiot. Sorry for wasting time here. Yes, closing!

@mlissner Don't blame yourself, we all make mistakes 😉
