### ISSUE TITLE
/redirect-to returns 404

### ISSUE THREAD

**Issue by codenirvana** [postmanlabs/httpbin#617]
All the `/redirect-to` endpoints are returning 404s.

```console
$ curl -v -X GET "http://httpbin.org/redirect-to?url=http://httpbin.org/get"
*   Trying 34.235.192.52...
* TCP_NODELAY set
* Connected to httpbin.org (34.235.192.52) port 80 (#0)
> GET /redirect-to?url=http://httpbin.org/get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: awselb/2.0
< Date: Sat, 20 Jun 2020 06:48:23 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host httpbin.org left intact
* Closing connection 0
```

**Comment by basrieter** [comment]
Same here

**Comment by convoliution** [comment]
@codenirvana I can't find information on who the current maintainer is for httpbin.
Since it's within the Postman org (which I think you're a member of), do you know who could resolve this?

**Comment by codenirvana** [comment]
cc. @kunagpal

**Comment by borkdude** [comment]
Also experiencing this problem with tests for https://github.com/borkdude/babashka.curl

**Comment by splitbrain** [comment]
Is @ken-reitz still the maintainer for httpbin? His website is still linked from httpbin.org but the repository now redirects to the postmanlabs organization?

**Comment by ddliu** [comment]
Same for `/redirect/{n}`.

**Comment by SmetDenis** [comment]
Hey,
Do you have any news/updates?

**Comment by jairhenrique** [comment]
@AbhiramH @ankitjaggi @Atishay4294 @bhargavkaranam @codenirvana @coditva @elssar @godfrzero @kunagpal @nik72619c @numaanashraf @pankajk07 @pradyumnawasthi @Prashansa-K @ritwijsinha @shamasis @sivcan @SueSmith @sujayvenaik @umeshp7 @vinitshahdeo @vkaegis @VShingala @xk0der

**Comment by marianopeck** [comment]
I have the same issue 
Any news? Do you know if there is a fork of this project more "maintained" ?

**Comment by felixonmars** [comment]
> Do you know if there is a fork of this project more "maintained" ?

Meanwhile I'm replacing it with httpbingo.org (https://github.com/mccutchen/go-httpbin) to get tests pass.

**Comment by felixonmars** [comment]
> > Do you know if there is a fork of this project more "maintained" ?
> 
> Meanwhile I'm replacing it with httpbingo.org (https://github.com/mccutchen/go-httpbin) to get tests pass.

Note that it's only working with https though. I'm using another one: httpbin.scrapinghub.com for http-only environments.

**Comment by kunagpal** [comment]
Everyone, we're sorry for the complete radio silence on this 😞. The `/redirect-to` endpoint had to be `404`'d due to an internal issue. As I write this, we're working on fixing and bringing this back up without further disruptions. Unfortunately, there's no E.T.A for this at the moment.

Thanks for hanging in there! 🧗

**Comment by splitbrain** [comment]
@kunagpal great that this issue is getting some attention, even though you're not explaining the radio silence. It would be nice to get some official statement about the state of this project and the support for it within the postman organization. I'd be interested to learn about the background on the transfer from @ken-reitz to your org and what your intentions are with this public service as a commercial entity.

**Comment by bryanmacfarlane** [comment]
@kunagpal any update on a fix?

**Comment by jeroen** [comment]
This mirror still seems to work: 

 - https://nghttp2.org/httpbin
 - https://httpbingo.org

**Comment by JustAnotherArchivist** [comment]
Same for `/absolute-redirect/{n}`.

**Comment by jrochkind** [comment]
August 2020 @kunagpal  wrote:

> Everyone, we're sorry for the complete radio silence on this 😞. The /redirect-to endpoint had to be 404'd due to an internal issue. As I write this, we're working on fixing and bringing this back up without further disruptions. Unfortunately, there's no E.T.A for this at the moment.

https://github.com/postmanlabs/httpbin/issues/617#issuecomment-668596347

About a year later... I guess it's probably not coming back?

**Comment by jimmywarting** [comment]
please return back to this project and fix this issue 🙏

**Comment by anshuljain03** [comment]
Sorry for not getting to this a lot sooner. This should be fixed now.

**Comment by dgw** [comment]
> Sorry for not getting to this a lot sooner. This should be fixed now.

Doesn't look like it's fixed. Or are we waiting for a rollout?

```
$ curl --head "http://httpbin.org/redirect-to?url=http://httpbin.org/get"
HTTP/1.1 404 Not Found
Server: awselb/2.0
Date: Tue, 05 Apr 2022 18:57:13 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
```

**Comment by anshuljain03** [comment]
@dgw should work now!

**Comment by dgw** [comment]
@anshuljain03 Tested again and yep, it does! 🥳
