### ISSUE TITLE
/headers Endpoint doesn't show all request headers

### ISSUE THREAD

**Issue by jackiecan** [postmanlabs/httpbin#715]
Hi, I tried to verify the usage of the X-Forwarded-For and Via-Header of my squid proxy with the `/headers` Endpoint which "Return the incoming request's HTTP headers." But the headers weren't present in the servers response like I would expect it. 
So I tested my proxy with a simple Python Webserver which indeed showed the presence of both headers. Is there some sort of preprocessing (maybe while Loadbalancing etc.) that removes headers? If so, maybe at least a notice of the possible removing of headers would be nice.

**Comment by Mossop** [comment]
See #300 and #71
