### ISSUE TITLE
setup httpbin.org service on another port too

### ISSUE THREAD

**Issue by gdamjan** [postmanlabs/httpbin#81]
setup httpbin.org service on another port too, 8080 for example, so that we can also test non standard ports in http

**Comment by PopFlamingo** [comment]
@kenneth-reitz @gdamjan Has this changed since 2013? I would have been interested to be able to test different ports on httpbin.org

**Comment by incfly** [comment]
+1. Hardcoded 80 has several limitations. I want to see a command line argument to able to specify the list of ports to listen on. This is very useful for networking testing requiring multiple ports.

**Comment by incfly** [comment]
I realize this FR is more than what I want. I just need to be able to customize httpbin binary itself with different port. Not the actual website.
